spring:
  data:
    cassandra:
      keyspace-name: taco_cloud
      username: <client-id>
      Password: <client-secret>
datastax.astra:
    secure-connect-bundle: <path-to-scb-from-src/main/resources/>